'use client';

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { TestResult, Language } from './MuscleTest';
import { muscleGroups } from '@/data/muscles';

interface PDFExportProps {
  patientName: string;
  results: TestResult[];
  lang: Language;
}

export default function PDFExport({ patientName, results, lang }: PDFExportProps) {
  const t = {
    en: {
      exportPDF: 'Export PDF',
      reportTitle: 'Muscle Strength Assessment Report',
      patient: 'Patient',
      date: 'Date',
      summary: 'Summary',
      totalTests: 'Total Tests',
      averageScore: 'Average Score',
      muscleGroup: 'Muscle Group',
      test: 'Test',
      score: 'Score',
      notes: 'Notes',
      scale: 'MRC Scale (0-5)',
      generatedBy: 'Generated by Gray Institute App',
    },
    uk: {
      exportPDF: 'Експорт PDF',
      reportTitle: 'Звіт про оцінку сили мязів',
      patient: 'Пацієнт',
      date: 'Дата',
      summary: 'Підсумок',
      totalTests: 'Всього тестів',
      averageScore: 'Середній бал',
      muscleGroup: 'Група мязів',
      test: 'Тест',
      score: 'Бал',
      notes: 'Нотатки',
      scale: 'Шкала MRC (0-5)',
      generatedBy: 'Згенеровано додатком Gray Institute',
    }
  };

  const scaleLegend = {
    en: [
      '0 = No contraction',
      '1 = Trace/Flicker',
      '2 = Active with gravity eliminated',
      '3 = Active against gravity',
      '4 = Active against some resistance',
      '5 = Normal strength'
    ],
    uk: [
      '0 = Без скорочення',
      '1 = Слабкий спазм',
      '2 = Активний без гравітації',
      '3 = Активний проти гравітації',
      '4 = Активний з опором',
      '5 = Нормальна сила'
    ]
  };

  const generatePDF = () => {
    const doc = new jsPDF();
    const currentDate = new Date().toLocaleDateString(lang === 'uk' ? 'uk-UA' : 'en-US');
    
    // Title
    doc.setFontSize(20);
    doc.text(t[lang].reportTitle, 14, 20);
    
    // Patient info
    doc.setFontSize(12);
    doc.text(`${t[lang].patient}: ${patientName || (lang === 'uk' ? 'Не вказано' : 'Not specified')}`, 14, 35);
    doc.text(`${t[lang].date}: ${currentDate}`, 14, 42);
    
    // Summary
    const totalTests = muscleGroups.reduce((sum, g) => sum + g.tests.length, 0);
    const completedCount = results.length;
    const averageScore = results.length > 0 
      ? (results.reduce((sum, r) => sum + r.score, 0) / results.length).toFixed(1)
      : '0';
    
    doc.setFontSize(14);
    doc.text(t[lang].summary, 14, 55);
    doc.setFontSize(11);
    doc.text(`${t[lang].totalTests}: ${completedCount}/${totalTests}`, 14, 62);
    doc.text(`${t[lang].averageScore}: ${averageScore}/5`, 14, 69);
    
    // Results table
    const tableData = results.map(result => {
      let groupName = '';
      let testName = '';
      
      for (const group of muscleGroups) {
        const test = group.tests.find(t => t.id === result.testId);
        if (test) {
          groupName = lang === 'uk' ? group.nameUk : group.nameEn;
          testName = lang === 'uk' ? test.nameUk : test.nameEn;
          break;
        }
      }
      
      return [
        groupName,
        testName,
        result.score.toString(),
        result.notes || '-'
      ];
    });
    
    autoTable(doc, {
      head: [[t[lang].muscleGroup, t[lang].test, t[lang].score, t[lang].notes]],
      body: tableData,
      startY: 75,
      styles: { fontSize: 10 },
      headStyles: { fillColor: [59, 130, 246] },
    });
    
    // Scale legend
    const finalY = (doc as any).lastAutoTable?.finalY || 150;
    doc.setFontSize(12);
    doc.text(t[lang].scale, 14, finalY + 15);
    doc.setFontSize(9);
    scaleLegend[lang].forEach((line, index) => {
      doc.text(line, 14, finalY + 22 + (index * 5));
    });
    
    // Footer
    doc.setFontSize(8);
    doc.text(t[lang].generatedBy, 14, 280);
    
    // Save
    const fileName = patientName 
      ? `${patientName.replace(/\s+/g, '_')}_muscle_assessment.pdf`
      : `muscle_assessment_${Date.now()}.pdf`;
    doc.save(fileName);
  };

  return (
    <button
      onClick={generatePDF}
      className="px-6 py-3 bg-red-500 text-white rounded-lg font-medium hover:bg-red-600 transition-colors flex items-center gap-2"
    >
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
      </svg>
      {t[lang].exportPDF}
    </button>
  );
}